name: C Program CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile all C files
        run: |
          mkdir -p bin
          for file in $(find . -name "*.c"); do
            exe_name=$(basename "$file" .c)
            gcc -Wall -Wextra "$file" -o "bin/$exe_name"
          done

      - name: Run the program
        run: ./program

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: program
          path: program
